USE DATABASE CHURN_DB;

CREATE OR REPLACE FILE FORMAT FF_TSV
  TYPE = CSV
  FIELD_DELIMITER = '\t'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE STG_CHURN_FILES
  FILE_FORMAT = FF_TSV;
